{% set name = "beanie-batteries-queue" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/beanie_batteries_queue-{{ version }}.tar.gz
  sha256: d63bd50a44bcaf7d89fda7d8bc165bbf5ecbbe012c440ba1955e9151d4e057b3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=3.2,<4
    - pip
  run:
    - python >={{ python_min }}
    - pydantic
    - beanie >=1.20

test:
  imports:
    - beanie_batteries_queue
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/roman-right/beanie_batteries_queue
  summary: Simple queue system for Beanie
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - awvwgk
