{% set name = "beanie-batteries-queue" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/beanie_batteries_queue-{{ version }}.tar.gz
  sha256: a5f548a2f040ca1737b239e2052316e331b491f36487578712d8e0525d2ecfcb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - flit-core >=3.2,<4
    - pip
  run:
    - python >=3.7
    - pydantic <2
    - beanie >=1.20

test:
  imports:
    - beanie_batteries_queue
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/roman-right/beanie_batteries_queue
  summary: Simple queue system for Beanie
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - awvwgk
